apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mkposture-dir
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: mkposture-dir
  template:
    metadata:
      labels:
        app: mkposture-dir
    spec:
      hostPID: true
      containers:
      - name: fixer
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          mkdir -p /host/var/lib/posture/analyzed_images && \
          chmod 0777 /host/var/lib/posture/analyzed_images && \
          echo "OK on $(cat /host/etc/hostname)" && \
          sleep 3600
        volumeMounts:
        - name: hostroot
          mountPath: /host
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
