# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: external_scaler.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65xternal_scaler.proto\x12\x0e\x65xternalscaler\"\xb7\x01\n\x0fScaledObjectRef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12L\n\x0fscaler_metadata\x18\x03 \x03(\x0b\x32\x33.externalscaler.ScaledObjectRef.ScalerMetadataEntry\x1a\x35\n\x13ScalerMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x10IsActiveResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"6\n\nMetricSpec\x12\x13\n\x0bmetric_name\x18\x01 \x01(\t\x12\x13\n\x0btarget_size\x18\x02 \x01(\x03\"I\n\x15GetMetricSpecResponse\x12\x30\n\x0cmetric_specs\x18\x01 \x03(\x0b\x32\x1a.externalscaler.MetricSpec\"d\n\x11GetMetricsRequest\x12:\n\x11scaled_object_ref\x18\x01 \x01(\x0b\x32\x1f.externalscaler.ScaledObjectRef\x12\x13\n\x0bmetric_name\x18\x02 \x01(\t\"8\n\x0bMetricValue\x12\x13\n\x0bmetric_name\x18\x01 \x01(\t\x12\x14\n\x0cmetric_value\x18\x02 \x01(\x03\"H\n\x12GetMetricsResponse\x12\x32\n\rmetric_values\x18\x01 \x03(\x0b\x32\x1b.externalscaler.MetricValue2\x8d\x02\n\x0e\x45xternalScaler\x12M\n\x08IsActive\x12\x1f.externalscaler.ScaledObjectRef\x1a .externalscaler.IsActiveResponse\x12W\n\rGetMetricSpec\x12\x1f.externalscaler.ScaledObjectRef\x1a%.externalscaler.GetMetricSpecResponse\x12S\n\nGetMetrics\x12!.externalscaler.GetMetricsRequest\x1a\".externalscaler.GetMetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'external_scaler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._loaded_options = None
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_SCALEDOBJECTREF']._serialized_start=42
  _globals['_SCALEDOBJECTREF']._serialized_end=225
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._serialized_start=172
  _globals['_SCALEDOBJECTREF_SCALERMETADATAENTRY']._serialized_end=225
  _globals['_ISACTIVERESPONSE']._serialized_start=227
  _globals['_ISACTIVERESPONSE']._serialized_end=261
  _globals['_METRICSPEC']._serialized_start=263
  _globals['_METRICSPEC']._serialized_end=317
  _globals['_GETMETRICSPECRESPONSE']._serialized_start=319
  _globals['_GETMETRICSPECRESPONSE']._serialized_end=392
  _globals['_GETMETRICSREQUEST']._serialized_start=394
  _globals['_GETMETRICSREQUEST']._serialized_end=494
  _globals['_METRICVALUE']._serialized_start=496
  _globals['_METRICVALUE']._serialized_end=552
  _globals['_GETMETRICSRESPONSE']._serialized_start=554
  _globals['_GETMETRICSRESPONSE']._serialized_end=626
  _globals['_EXTERNALSCALER']._serialized_start=629
  _globals['_EXTERNALSCALER']._serialized_end=898
# @@protoc_insertion_point(module_scope)
