apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-jobs
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-0:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            resources:
              limits:
                cpu: "1"
                memory: "512Mi"

        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: posture-analyzer
                topologyKey: "kubernetes.io/hostname"

          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: posture/eligible
                      operator: In
                      values:
                        - "true"
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-1"]
              - weight: 90
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-2"]
              - weight: 80
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-3"]
              - weight: 70
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-4"]
              - weight: 60
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-5"]
              - weight: 50
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-6"]
              - weight: 40
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-7"]
              - weight: 30
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-8"]
              - weight: 20
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-9"]
              - weight: 10
                preference:
                  matchExpressions:
                    - key: posture/slot
                      operator: In
                      values: ["slot-10"]

  pollingInterval: 10
  maxReplicaCount: 10
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  triggers:
    - type: external
      metadata:
        # 🧠 Updated: point directly to local scaler (NUC)
        scalerAddress: 192.168.1.176:8081
        metricName: available_node_count_30s

