# ============================================================
#  Posture Analyzer ScaledJobs (10 separate images)
#  Each represents one "queued work item" (pod)
#  Always choose an eligible node, prefer lowest slot number,
#  and let K8s randomly pick if multiple nodes share same slot.
# ============================================================

# ---- Job 0 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-0
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-0:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 1 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-1
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-1:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 2 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-2
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-2:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 3 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-3
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-3:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 4 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-4
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-4:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 5 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-5
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-5:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 6 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-6
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-6:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 7 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-7
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-7:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 8 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-8
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-8:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s

---

# ---- Job 9 ----
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: posture-analyzer-job-9
  namespace: posture
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: posture-analyzer
      spec:
        restartPolicy: Never
        containers:
          - name: analyzer
            image: shahroz90/posture-analyzer-pi1-9:latest
            imagePullPolicy: Always
            env:
              - name: NODE_NAME
                valueFrom: {fieldRef: {fieldPath: spec.nodeName}}
              - name: POD_NAME
                valueFrom: {fieldRef: {fieldPath: metadata.name}}
            resources:
              limits: {cpu: "1", memory: "512Mi"}
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {app: posture-analyzer}}
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - {key: posture/eligible, operator: In, values: ["true"]}
            preferredDuringSchedulingIgnoredDuringExecution:
              - {weight: 100, preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-1"]}]}}
              - {weight: 90,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-2"]}]}}
              - {weight: 80,  preference: {matchExpressions: [{key: posture/slot, operator: In, values: ["slot-3"]}]}}
  pollingInterval: 10
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  triggers:
    - type: external
      metadata:
        scalerAddress: posture-external-scaler.posture.svc.cluster.local:8080
        metricName: available_node_count_30s
